#ifndef SUPPORTED_OFLAG
#define SUPPORTED_OFLAG(name)
#define SUPPORTED_OFLAG_NOT_PREDEFINED
#endif

#ifndef UNSUPPORTED_OFLAG
#define UNSUPPORTED_OFLAG(name)
#define UNSUPPORTED_OFLAG_NOT_PREDEFINED
#endif

SUPPORTED_OFLAG(O_EXCL)
SUPPORTED_OFLAG(O_CREAT)
SUPPORTED_OFLAG(O_TRUNC)
SUPPORTED_OFLAG(O_NOCTTY)
SUPPORTED_OFLAG(O_CLOEXEC)
SUPPORTED_OFLAG(O_NONBLOCK)
SUPPORTED_OFLAG(O_APPEND)
SUPPORTED_OFLAG(O_SYNC)
SUPPORTED_OFLAG(O_RSYNC)
SUPPORTED_OFLAG(O_DSYNC)
SUPPORTED_OFLAG(O_NOFOLLOW)
SUPPORTED_OFLAG(O_DIRECT)
SUPPORTED_OFLAG(O_NOCACHE)
SUPPORTED_OFLAG(O_DIRECTORY)

UNSUPPORTED_OFLAG(O_NOTRAVERSE)

#ifdef SUPPORTED_OFLAG_NOT_PREDEFINED
#undef SUPPORTED_OFLAG_NOT_PREDEFINED
#undef SUPPORTED_OFLAG
#endif

#ifdef UNSUPPORTED_OFLAG_NOT_PREDEFINED
#undef UNSUPPORTED_OFLAG_NOT_PREDEFINED
#undef UNSUPPORTED_OFLAG
#endif

// RW flags (O_RDONLY, O_WRONLY, O_RDWR) are not enums.
#ifndef SUPPORTED_RWOFLAG
#define SUPPORTED_RWOFLAG(name)
#define SUPPORTED_RWOFLAG_NOT_PREDEFINED
#endif

SUPPORTED_RWOFLAG(O_RDONLY)
SUPPORTED_RWOFLAG(O_WRONLY)
SUPPORTED_RWOFLAG(O_RDWR)

#ifdef SUPPORTED_RWOFLAG_NOT_PREDEFINED
#undef SUPPORTED_RWOFLAG_NOT_PREDEFINED
#undef SUPPORTED_RWOFLAG
#endif

#ifndef SUPPORTED_FCNTL
#define SUPPORTED_FCNTL(name)
#define SUPPORTED_FCNTL_NOT_PREDEFINED
#endif

#ifndef UNSUPPORTED_FCNTL
#define UNSUPPORTED_FCNTL(name)
#define UNSUPPORTED_FCNTL_NOT_PREDEFINED
#endif

SUPPORTED_FCNTL(F_DUPFD)
SUPPORTED_FCNTL(F_GETFD)
SUPPORTED_FCNTL(F_SETFD)
SUPPORTED_FCNTL(F_GETFL)
SUPPORTED_FCNTL(F_SETFL)
SUPPORTED_FCNTL(F_GETLK)
SUPPORTED_FCNTL(F_SETLK)
SUPPORTED_FCNTL(F_SETLKW)
SUPPORTED_FCNTL(F_DUPFD_CLOEXEC)

#ifdef SUPPORTED_FCNTL_NOT_PREDEFINED
#undef SUPPORTED_FCNTL_NOT_PREDEFINED
#undef SUPPORTED_FCNTL
#endif

#ifdef UNSUPPORTED_FCNTL_NOT_PREDEFINED
#undef UNSUPPORTED_FCNTL_NOT_PREDEFINED
#undef UNSUPPORTED_FCNTL
#endif