#ifndef SUPPORTED_IFLAG
#define SUPPORTED_IFLAG(code)
#define SUPPORTED_IFLAG_NOT_PREDEFINED
#endif

SUPPORTED_IFLAG(IGNBRK)
SUPPORTED_IFLAG(BRKINT)
SUPPORTED_IFLAG(IGNPAR)
SUPPORTED_IFLAG(PARMRK)
SUPPORTED_IFLAG(INPCK)
SUPPORTED_IFLAG(ISTRIP)
SUPPORTED_IFLAG(INLCR)
SUPPORTED_IFLAG(IGNCR)
SUPPORTED_IFLAG(ICRNL)
SUPPORTED_IFLAG(IUCLC)
SUPPORTED_IFLAG(IXON)
SUPPORTED_IFLAG(IXANY)
SUPPORTED_IFLAG(IXOFF)

#ifdef SUPPORTED_IFLAG_NOT_PREDEFINED
#undef SUPPORTED_IFLAG_NOT_PREDEFINED
#undef SUPPORTED_IFLAG
#endif

#ifndef SUPPORTED_OFLAG
#define SUPPORTED_OFLAG(code)
#define SUPPORTED_OFLAG_NOT_PREDEFINED
#endif

SUPPORTED_OFLAG(OPOST)
SUPPORTED_OFLAG(OLCUC)
SUPPORTED_OFLAG(ONLCR)
SUPPORTED_OFLAG(OCRNL)
SUPPORTED_OFLAG(ONOCR)
SUPPORTED_OFLAG(ONLRET)
SUPPORTED_OFLAG(OFILL)
SUPPORTED_OFLAG(OFDEL)
SUPPORTED_OFLAG(NLDLY)
SUPPORTED_OFLAG(NL0)
SUPPORTED_OFLAG(NL1)
SUPPORTED_OFLAG(CRDLY)
SUPPORTED_OFLAG(CR0)
SUPPORTED_OFLAG(CR1)
SUPPORTED_OFLAG(CR2)
SUPPORTED_OFLAG(CR3)
SUPPORTED_OFLAG(TABDLY)
SUPPORTED_OFLAG(TAB0)
SUPPORTED_OFLAG(TAB1)
SUPPORTED_OFLAG(TAB2)
SUPPORTED_OFLAG(TAB3)
SUPPORTED_OFLAG(BSDLY)
SUPPORTED_OFLAG(BS0)
SUPPORTED_OFLAG(BS1)
SUPPORTED_OFLAG(VTDLY)
SUPPORTED_OFLAG(VT0)
SUPPORTED_OFLAG(VT1)
SUPPORTED_OFLAG(FFDLY)
SUPPORTED_OFLAG(FF0)
SUPPORTED_OFLAG(FF1)

#ifdef SUPPORTED_OFLAG_NOT_PREDEFINED
#undef SUPPORTED_OFLAG_NOT_PREDEFINED
#undef SUPPORTED_OFLAG
#endif

#ifndef SUPPORTED_CFLAG
#define SUPPORTED_CFLAG(code)
#define SUPPORTED_CFLAG_NOT_PREDEFINED
#endif

#ifndef UNSUPPORTED_CFLAG
#define UNSUPPORTED_CFLAG(code)
#define UNSUPPORTED_CFLAG_NOT_PREDEFINED
#endif

SUPPORTED_CFLAG(CBAUD)

SUPPORTED_CFLAG(B0)
SUPPORTED_CFLAG(B50)
SUPPORTED_CFLAG(B75)
SUPPORTED_CFLAG(B110)
SUPPORTED_CFLAG(B134)
SUPPORTED_CFLAG(B150)
SUPPORTED_CFLAG(B200)
SUPPORTED_CFLAG(B300)
SUPPORTED_CFLAG(B600)
SUPPORTED_CFLAG(B1200)
SUPPORTED_CFLAG(B1800)
SUPPORTED_CFLAG(B2400)
SUPPORTED_CFLAG(B4800)
SUPPORTED_CFLAG(B9600)
SUPPORTED_CFLAG(B19200)
SUPPORTED_CFLAG(B38400)
SUPPORTED_CFLAG(B57600)
SUPPORTED_CFLAG(B115200)
SUPPORTED_CFLAG(B230400)
// Not directly supported but emulated.
//UNSUPPORTED_CFLAG(B31250)

SUPPORTED_CFLAG(CSIZE)
SUPPORTED_CFLAG(CS5)
SUPPORTED_CFLAG(CS6)
SUPPORTED_CFLAG(CS7)
SUPPORTED_CFLAG(CS8)
SUPPORTED_CFLAG(CSTOPB)
SUPPORTED_CFLAG(CREAD)
SUPPORTED_CFLAG(PARENB)
SUPPORTED_CFLAG(PARODD)
SUPPORTED_CFLAG(HUPCL)
SUPPORTED_CFLAG(CLOCAL)
UNSUPPORTED_CFLAG(XLOBLK)
// Can be emulated using CRTSCTS.
//UNSUPPORTED_CFLAG(CTSFLOW)
//UNSUPPORTED_CFLAG(RTSFLOW)
SUPPORTED_CFLAG(CRTSCTS)

#ifdef SUPPORTED_CFLAG_NOT_PREDEFINED
#undef SUPPORTED_CFLAG_NOT_PREDEFINED
#undef SUPPORTED_CFLAG
#endif

#ifdef UNSUPPORTED_CFLAG_NOT_PREDEFINED
#undef UNSUPPORTED_CFLAG_NOT_PREDEFINED
#undef UNSUPPORTED_CFLAG
#endif

#ifndef SUPPORTED_LFLAG
#define SUPPORTED_LFLAG(code)
#define SUPPORTED_LFLAG_NOT_PREDEFINED
#endif

SUPPORTED_LFLAG(ISIG)
SUPPORTED_LFLAG(ICANON)
SUPPORTED_LFLAG(XCASE)
SUPPORTED_LFLAG(ECHO)
SUPPORTED_LFLAG(ECHOE)
SUPPORTED_LFLAG(ECHOK)
SUPPORTED_LFLAG(ECHONL)
SUPPORTED_LFLAG(NOFLSH)
SUPPORTED_LFLAG(TOSTOP)
SUPPORTED_LFLAG(IEXTEN)
SUPPORTED_LFLAG(ECHOCTL)
SUPPORTED_LFLAG(ECHOPRT)
SUPPORTED_LFLAG(ECHOKE)
SUPPORTED_LFLAG(FLUSHO)
SUPPORTED_LFLAG(PENDIN)

#ifdef SUPPORTED_LFLAG_NOT_PREDEFINED
#undef SUPPORTED_LFLAG_NOT_PREDEFINED
#undef SUPPORTED_LFLAG
#endif

#ifndef SUPPORTED_CC
#define SUPPORTED_CC(code)
#define SUPPORTED_CC_NOT_PREDEFINED
#endif

SUPPORTED_CC(VINTR)
SUPPORTED_CC(VQUIT)
SUPPORTED_CC(VERASE)
SUPPORTED_CC(VKILL)
SUPPORTED_CC(VEOF)
SUPPORTED_CC(VEOL)
SUPPORTED_CC(VMIN)
SUPPORTED_CC(VTIME)
SUPPORTED_CC(VEOL2)
SUPPORTED_CC(VSWTCH)
SUPPORTED_CC(VSTART)
SUPPORTED_CC(VSTOP)
SUPPORTED_CC(VSUSP)

#ifdef SUPPORTED_CC_NOT_PREDEFINED
#undef SUPPORTED_CC_NOT_PREDEFINED
#undef SUPPORTED_CC
#endif