#ifndef SUPPORTED_POLL_FLAG
#define SUPPORTED_POLL_FLAG(name)
#define SUPPORTED_POLL_FLAG_NOT_PREDEFINED
#endif

SUPPORTED_POLL_FLAG(POLLIN)
SUPPORTED_POLL_FLAG(POLLOUT)
SUPPORTED_POLL_FLAG(POLLRDBAND)
SUPPORTED_POLL_FLAG(POLLWRBAND)
SUPPORTED_POLL_FLAG(POLLPRI)
SUPPORTED_POLL_FLAG(POLLERR)
SUPPORTED_POLL_FLAG(POLLHUP)
SUPPORTED_POLL_FLAG(POLLNVAL)

#ifdef SUPPORTED_POLL_FLAG_NOT_PREDEFINED
#undef SUPPORTED_POLL_FLAG_NOT_PREDEFINED
#undef SUPPORTED_POLL_FLAG
#endif