#ifndef SUPPORTED_RLIMIT
#define SUPPORTED_RLIMIT(name)
#define SUPPORTED_RLIMIT_NOT_PREDEFINED
#endif

#ifndef UNSUPPORTED_RLIMIT
#define UNSUPPORTED_RLIMIT(name)
#define UNSUPPORTED_RLIMIT_NOT_PREDEFINED
#endif

SUPPORTED_RLIMIT(RLIMIT_CORE)
SUPPORTED_RLIMIT(RLIMIT_CPU)
SUPPORTED_RLIMIT(RLIMIT_DATA)
SUPPORTED_RLIMIT(RLIMIT_FSIZE)
SUPPORTED_RLIMIT(RLIMIT_NOFILE)
SUPPORTED_RLIMIT(RLIMIT_STACK)
SUPPORTED_RLIMIT(RLIMIT_AS)

UNSUPPORTED_RLIMIT(RLIMIT_NOVMON)

#ifdef SUPPORTED_RLIMIT_NOT_PREDEFINED
#undef SUPPORTED_RLIMIT_NOT_PREDEFINED
#undef SUPPORTED_RLIMIT
#endif

#ifdef UNSUPPORTED_RLIMIT_NOT_PREDEFINED
#undef UNSUPPORTED_RLIMIT_NOT_PREDEFINED
#undef UNSUPPORTED_RLIMIT
#endif